### ISSUE TITLE
The video download link for this post is not available.

### ISSUE THREAD

**Issue by Arish68** [riad-azz/instagram-video-downloader#5] opened 2023-08-09 05:07 UTC
How can I resolve this issue? I have also hosted it on my AWS Amplify for Next.js (version 13), but the problem still persists.
![Capture](https://github.com/riad-azz/instagram-video-downloader/assets/41190268/9329c80d-2765-4290-b304-bfe028acab33)

**Comment by riad-azz** [comment] 2023-08-09 09:30
Hello there, This is not an issue this is an error by design.
The application only scrapes the post page and if the LD+JSON is not included in the post it raises this error.
This issue is a duplicate of : [Always return "The video download link for this post is not available" #2 ](https://github.com/riad-azz/instagram-video-downloader/issues/2)

However if you really want to "fix it", try using this old version where you can use Instagram API with your account : [Old commit with User API](https://github.com/riad-azz/instagram-video-downloader/tree/35e10c1f0fc2d59ef94b1656892abf48ec05f091)

**Disclaimer**: there is a very high chance of the account being banned in case of being detected so use at your own risk.

**Closed by riad-azz** 2023-08-09 09:30 UTC
